# This file was auto-generated using a vim macro, because I'm lazy haha
touch bandit34.txt
touch bandit33.txt
touch bandit32.txt
touch bandit31.txt
touch bandit30.txt
touch bandit29.txt
touch bandit28.txt
touch bandit27.txt
touch bandit26.txt
touch bandit25.txt
touch bandit24.txt
touch bandit23.txt
touch bandit22.txt
touch bandit21.txt
touch bandit20.txt
touch bandit19.txt
touch bandit18.txt
touch bandit17.txt
touch bandit16.txt
touch bandit15.txt
touch bandit14.txt
touch bandit13.txt
touch bandit12.txt
touch bandit11.txt
touch bandit10.txt
touch bandit9.txt
touch bandit8.txt
touch bandit7.txt
touch bandit6.txt
touch bandit5.txt
touch bandit4.txt
touch bandit3.txt
touch bandit2.txt
touch bandit1.txt
